Teamtable <- function(TeamsOa){
TeamsOa$full_name[TeamsOa$full_name == "Abilene Christian Wildcats"] <- "Abilene Christian"
TeamsOa$full_name[TeamsOa$full_name == "Air Force Falcons"] <- "Air Force"
TeamsOa$full_name[TeamsOa$full_name == "Akron Zips"] <- "Akron"
TeamsOa$full_name[TeamsOa$full_name == "Alabama A&M Bulldogs"] <- "Alabama A&M"
TeamsOa$full_name[TeamsOa$full_name == "Alabama Crimson Tide"] <- "Alabama"
TeamsOa$full_name[TeamsOa$full_name == "Alabama St Hornets"] <- "Alabama St."
TeamsOa$full_name[TeamsOa$full_name == "Albany Great Danes"] <- "Albany"
TeamsOa$full_name[TeamsOa$full_name == "Alcorn St Braves"] <- "Alcorn St."
TeamsOa$full_name[TeamsOa$full_name == "American Eagles"] <- "American"
TeamsOa$full_name[TeamsOa$full_name == "Appalachian St Mountaineers"] <- "Appalachian St."
TeamsOa$full_name[TeamsOa$full_name == "Arizona St Sun Devils"] <- "Arizona St."
TeamsOa$full_name[TeamsOa$full_name == "Arizona Wildcats"] <- "Arizona"
TeamsOa$full_name[TeamsOa$full_name == "Arkansas Razorbacks"] <- "Arkansas"
TeamsOa$full_name[TeamsOa$full_name == "Arkansas St Red Wolves"] <- "Arkansas St."
TeamsOa$full_name[TeamsOa$full_name == "Arkansas-Little Rock Trojans"] <- "Arkansas-Little Rock"
TeamsOa$full_name[TeamsOa$full_name == "Arkansas-Pine Bluff Golden Lions"] <- "Arkansas-Pine Bluff"
TeamsOa$full_name[TeamsOa$full_name == "Army Knights"] <- "Army"
TeamsOa$full_name[TeamsOa$full_name == "Auburn Tigers"] <- "Auburn"
TeamsOa$full_name[TeamsOa$full_name == "Austin Peay Governors"] <- "Austin Peay"
TeamsOa$full_name[TeamsOa$full_name == "BYU Cougars"] <- "BYU"
TeamsOa$full_name[TeamsOa$full_name == "Baldwin Wallace Yellow Jackets"] <- "Baldwin Wallace"
TeamsOa$full_name[TeamsOa$full_name == "Ball State Cardinals"] <- "Ball St."
TeamsOa$full_name[TeamsOa$full_name == "Baylor Bears"] <- "Baylor"
TeamsOa$full_name[TeamsOa$full_name == "Bellarmine Knights"] <- "Bellarmine"
TeamsOa$full_name[TeamsOa$full_name == "Belmont Bruins"] <- "Belmont"
TeamsOa$full_name[TeamsOa$full_name == "Bethune-Cookman Wildcats"] <- "Bethune-Cookman"
TeamsOa$full_name[TeamsOa$full_name == "Binghamton Bearcats"] <- "Binghamton"
TeamsOa$full_name[TeamsOa$full_name == "Boise State Broncos"] <- "Boise St."
TeamsOa$full_name[TeamsOa$full_name == "Boston College Eagles"] <- "Boston College"
TeamsOa$full_name[TeamsOa$full_name == "Boston Univ. Terriers"] <- "Boston Univ."
TeamsOa$full_name[TeamsOa$full_name == "Bowling Green Falcons"] <- "Bowling Green"
TeamsOa$full_name[TeamsOa$full_name == "Bradley Braves"] <- "Bradley"
TeamsOa$full_name[TeamsOa$full_name == "Brescia Bearcats"] <- "Brescia"
TeamsOa$full_name[TeamsOa$full_name == "Brown Bears"] <- "Brown"
TeamsOa$full_name[TeamsOa$full_name == "Bryant Bulldogs"] <- "Bryant"
TeamsOa$full_name[TeamsOa$full_name == "Bucknell Bison"] <- "Bucknell"
TeamsOa$full_name[TeamsOa$full_name == "Buffalo Bulls"] <- "Buffalo"
TeamsOa$full_name[TeamsOa$full_name == "Butler Bulldogs"] <- "Butler"
TeamsOa$full_name[TeamsOa$full_name == "CSU Bakersfield Roadrunners"] <- "CSU Bakersfield"
TeamsOa$full_name[TeamsOa$full_name == "CSU Fullerton Titans"] <- "CSU Fullerton"
TeamsOa$full_name[TeamsOa$full_name == "CSU Northridge Matadors"] <- "CSU Northridge"
TeamsOa$full_name[TeamsOa$full_name == "Cal Baptist Lancers"] <- "Cal Baptist"
TeamsOa$full_name[TeamsOa$full_name == "Cal Poly Mustangs"] <- "Cal Poly"
TeamsOa$full_name[TeamsOa$full_name == "California Golden Bears"] <- "California"
TeamsOa$full_name[TeamsOa$full_name == "Campbell Fighting Camels"] <- "Campbell"
TeamsOa$full_name[TeamsOa$full_name == "Canisius Golden Griffins"] <- "Canisius"
TeamsOa$full_name[TeamsOa$full_name == "Central Arkansas Bears"] <- "Central Arkansas"
TeamsOa$full_name[TeamsOa$full_name == "Central Connecticut St Blue Devils"] <- "Central Connecticut St"
TeamsOa$full_name[TeamsOa$full_name == "Central Michigan Chippewas"] <- "Central Michigan"
TeamsOa$full_name[TeamsOa$full_name == "Charleston Cougars"] <- "Charleston"
TeamsOa$full_name[TeamsOa$full_name == "Charleston Southern Buccaneers"] <- "Charleston Southern"
TeamsOa$full_name[TeamsOa$full_name == "Charlotte 49ers"] <- "Charlotte"
TeamsOa$full_name[TeamsOa$full_name == "Chattanooga Mocs"] <- "Chattanooga"
TeamsOa$full_name[TeamsOa$full_name == "Chicago St Cougars"] <- "Chicago St."
TeamsOa$full_name[TeamsOa$full_name == "Cincinnati Bearcats"] <- "Cincinnati"
TeamsOa$full_name[TeamsOa$full_name == "Cincinnati Clermont"] <- "Cincinnati Clermont"
TeamsOa$full_name[TeamsOa$full_name == "Clemson Tigers"] <- "Clemson"
TeamsOa$full_name[TeamsOa$full_name == "Cleveland St Vikings"] <- "Cleveland St."
TeamsOa$full_name[TeamsOa$full_name == "Clinton Bears"] <- "Clinton"
TeamsOa$full_name[TeamsOa$full_name == "Coastal Carolina Chanticleers"] <- "Coastal Carolina"
TeamsOa$full_name[TeamsOa$full_name == "Colgate Raiders"] <- "Colgate"
TeamsOa$full_name[TeamsOa$full_name == "Colorado Buffaloes"] <- "Colorado"
TeamsOa$full_name[TeamsOa$full_name == "Colorado St Rams"] <- "Colorado St."
TeamsOa$full_name[TeamsOa$full_name == "Columbia Lions"] <- "Columbia"
TeamsOa$full_name[TeamsOa$full_name == "Coppin St Eagles"] <- "Coppin St"
TeamsOa$full_name[TeamsOa$full_name == "Cornell Big Red"] <- "Cornell"
TeamsOa$full_name[TeamsOa$full_name == "Creighton Bluejays"] <- "Creighton"
TeamsOa$full_name[TeamsOa$full_name == "Dartmouth Big Green"] <- "Dartmouth"
TeamsOa$full_name[TeamsOa$full_name == "Davidson Wildcats"] <- "Davidson"
TeamsOa$full_name[TeamsOa$full_name == "Dayton Flyers"] <- "Dayton"
TeamsOa$full_name[TeamsOa$full_name == "DePaul Blue Demons"] <- "DePaul"
TeamsOa$full_name[TeamsOa$full_name == "Defiance College Yellow Jackets"] <- "Defiance College"
TeamsOa$full_name[TeamsOa$full_name == "Delaware Blue Hens"] <- "Delaware"
TeamsOa$full_name[TeamsOa$full_name == "Delaware St Hornets"] <- "Delaware St."
TeamsOa$full_name[TeamsOa$full_name == "Denver Pioneers"] <- "Denver"
TeamsOa$full_name[TeamsOa$full_name == "Detroit Mercy Titans"] <- "Detroit Mercy"
TeamsOa$full_name[TeamsOa$full_name == "Dixie State Trailblazers"] <- "Dixie State"
TeamsOa$full_name[TeamsOa$full_name == "Drake Bulldogs"] <- "Drake"
TeamsOa$full_name[TeamsOa$full_name == "Drexel Dragons"] <- "Drexel"
TeamsOa$full_name[TeamsOa$full_name == "Duke Blue Devils"] <- "Duke"
TeamsOa$full_name[TeamsOa$full_name == "Duquesne Dukes"] <- "Duquesne"
TeamsOa$full_name[TeamsOa$full_name == "East Carolina Pirates"] <- "East Carolina"
TeamsOa$full_name[TeamsOa$full_name == "East Tennessee St Buccaneers"] <- "East Tennessee St"
TeamsOa$full_name[TeamsOa$full_name == "East Texas A&M Lions"] <- "East Texas A&M"
TeamsOa$full_name[TeamsOa$full_name == "Eastern Illinois Panthers"] <- "Eastern Illinois"
TeamsOa$full_name[TeamsOa$full_name == "Eastern Kentucky Colonels"] <- "Eastern Kentucky"
TeamsOa$full_name[TeamsOa$full_name == "Eastern Michigan Eagles"] <- "Eastern Michigan"
TeamsOa$full_name[TeamsOa$full_name == "Eastern Washington Eagles"] <- "Eastern Washington"
TeamsOa$full_name[TeamsOa$full_name == "Elon Phoenix"] <- "Elon"
TeamsOa$full_name[TeamsOa$full_name == "Evansville Purple Aces"] <- "Evansville"
TeamsOa$full_name[TeamsOa$full_name == "Fairfield Stags"] <- "Fairfield"
TeamsOa$full_name[TeamsOa$full_name == "Fairleigh Dickinson Knights"] <- "Fairleigh Dickinson"
TeamsOa$full_name[TeamsOa$full_name == "Florida A&M Rattlers"] <- "Florida A&M"
TeamsOa$full_name[TeamsOa$full_name == "Florida Atlantic Owls"] <- "Florida Atlantic"
TeamsOa$full_name[TeamsOa$full_name == "Florida Gators"] <- "Florida"
TeamsOa$full_name[TeamsOa$full_name == "Florida Gulf Coast Eagles"] <- "Florida Gulf Coast"
TeamsOa$full_name[TeamsOa$full_name == "Florida Int'l Golden Panthers"] <- "Florida Int'l"
TeamsOa$full_name[TeamsOa$full_name == "Florida St Seminoles"] <- "Florida St."
TeamsOa$full_name[TeamsOa$full_name == "Fordham Rams"] <- "Fordham"
TeamsOa$full_name[TeamsOa$full_name == "Fort Wayne Mastodons"] <- "Fort Wayne"
TeamsOa$full_name[TeamsOa$full_name == "Fresno St Bulldogs"] <- "Fresno St."
TeamsOa$full_name[TeamsOa$full_name == "Furman Paladins"] <- "Furman"
TeamsOa$full_name[TeamsOa$full_name == "GW Revolutionaries"] <- "GW"
TeamsOa$full_name[TeamsOa$full_name == "Gallaudet Bison"] <- "Gallaudet"
TeamsOa$full_name[TeamsOa$full_name == "Gardner-Webb Bulldogs"] <- "Gardner-Webb"
TeamsOa$full_name[TeamsOa$full_name == "George Mason Patriots"] <- "George Mason"
TeamsOa$full_name[TeamsOa$full_name == "Georgetown Hoyas"] <- "Georgetown"
TeamsOa$full_name[TeamsOa$full_name == "Georgia Bulldogs"] <- "Georgia"
TeamsOa$full_name[TeamsOa$full_name == "Georgia Southern Eagles"] <- "Georgia Southern"
TeamsOa$full_name[TeamsOa$full_name == "Georgia Southwestern State Hurricanes"] <- "Georgia Southwestern St."
TeamsOa$full_name[TeamsOa$full_name == "Georgia St Panthers"] <- "Georgia St."
TeamsOa$full_name[TeamsOa$full_name == "Georgia Tech Yellow Jackets"] <- "Georgia Tech"
TeamsOa$full_name[TeamsOa$full_name == "Gonzaga Bulldogs"] <- "Gonzaga"
TeamsOa$full_name[TeamsOa$full_name == "Grambling St Tigers"] <- "Grambling St"
TeamsOa$full_name[TeamsOa$full_name == "Grand Canyon Antelopes"] <- "Grand Canyon"
TeamsOa$full_name[TeamsOa$full_name == "Green Bay Phoenix"] <- "Green Bay"
TeamsOa$full_name[TeamsOa$full_name == "Hampton Pirates"] <- "Hampton"
TeamsOa$full_name[TeamsOa$full_name == "Hartford Hawks"] <- "Hartford"
TeamsOa$full_name[TeamsOa$full_name == "Harvard Crimson"] <- "Harvard"
TeamsOa$full_name[TeamsOa$full_name == "Hawai'i Rainbow Warriors"] <- "Hawai'i"
TeamsOa$full_name[TeamsOa$full_name == "High Point Panthers"] <- "High Point"
TeamsOa$full_name[TeamsOa$full_name == "Hofstra Pride"] <- "Hofstra"
TeamsOa$full_name[TeamsOa$full_name == "Holy Cross Crusaders"] <- "Holy Cross"
TeamsOa$full_name[TeamsOa$full_name == "Houston Christian Huskies"] <- "Houston Christian"
TeamsOa$full_name[TeamsOa$full_name == "Houston Cougars"] <- "Houston"
TeamsOa$full_name[TeamsOa$full_name == "Howard Bison"] <- "Howard"
TeamsOa$full_name[TeamsOa$full_name == "IUPUI Jaguars"] <- "IUPUI"
TeamsOa$full_name[TeamsOa$full_name == "Idaho State Bengals"] <- "Idaho St."
TeamsOa$full_name[TeamsOa$full_name == "Idaho Vandals"] <- "Idaho"
TeamsOa$full_name[TeamsOa$full_name == "Illinois Fighting Illini"] <- "Illinois"
TeamsOa$full_name[TeamsOa$full_name == "Illinois St Redbirds"] <- "Illinois St."
TeamsOa$full_name[TeamsOa$full_name == "Immaculata Mighty Macs"] <- "Immaculata"
TeamsOa$full_name[TeamsOa$full_name == "Incarnate Word Cardinals"] <- "Incarnate Word"
TeamsOa$full_name[TeamsOa$full_name == "Indiana Hoosiers"] <- "Indiana"
TeamsOa$full_name[TeamsOa$full_name == "Indiana St Sycamores"] <- "Indiana St."
TeamsOa$full_name[TeamsOa$full_name == "Iona Gaels"] <- "Iona"
TeamsOa$full_name[TeamsOa$full_name == "Iowa Hawkeyes"] <- "Iowa"
TeamsOa$full_name[TeamsOa$full_name == "Iowa State Cyclones"] <- "Iowa St."
TeamsOa$full_name[TeamsOa$full_name == "Jackson St Tigers"] <- "Jackson St."
TeamsOa$full_name[TeamsOa$full_name == "Jacksonville Dolphins"] <- "Jacksonville"
TeamsOa$full_name[TeamsOa$full_name == "Jacksonville St Gamecocks"] <- "Jacksonville St."
TeamsOa$full_name[TeamsOa$full_name == "James Madison Dukes"] <- "James Madison"
TeamsOa$full_name[TeamsOa$full_name == "John Jay College Bloodhounds"] <- "John Jay College"
TeamsOa$full_name[TeamsOa$full_name == "Johnson And Wales (NC) Wildcats"] <- "Johnson And Wales (NC)"
TeamsOa$full_name[TeamsOa$full_name == "Kansas Christian Falcons"] <- "Kansas Christian"
TeamsOa$full_name[TeamsOa$full_name == "Kansas Jayhawks"] <- "Kansas"
TeamsOa$full_name[TeamsOa$full_name == "Kansas St Wildcats"] <- "Kansas St."
TeamsOa$full_name[TeamsOa$full_name == "Kennesaw St Owls"] <- "Kennesaw St"
TeamsOa$full_name[TeamsOa$full_name == "Kent State Golden Flashes"] <- "Kent St."
TeamsOa$full_name[TeamsOa$full_name == "Kentucky Wildcats"] <- "Kentucky"
TeamsOa$full_name[TeamsOa$full_name == "LIU Sharks"] <- "LIU"
TeamsOa$full_name[TeamsOa$full_name == "LSU Tigers"] <- "LSU"
TeamsOa$full_name[TeamsOa$full_name == "La Salle Explorers"] <- "La Salle"
TeamsOa$full_name[TeamsOa$full_name == "Lafayette Leopards"] <- "Lafayette"
TeamsOa$full_name[TeamsOa$full_name == "Lamar Cardinals"] <- "Lamar"
TeamsOa$full_name[TeamsOa$full_name == "Le Moyne Dolphins"] <- "Le Moyne"
TeamsOa$full_name[TeamsOa$full_name == "Lehigh Mountain Hawks"] <- "Lehigh"
TeamsOa$full_name[TeamsOa$full_name == "Liberty Flames"] <- "Liberty"
TeamsOa$full_name[TeamsOa$full_name == "Lindenwood Lions"] <- "Lindenwood"
TeamsOa$full_name[TeamsOa$full_name == "Lipscomb Bisons"] <- "Lipscomb"
TeamsOa$full_name[TeamsOa$full_name == "Long Beach St 49ers"] <- "Long Beach St."
TeamsOa$full_name[TeamsOa$full_name == "Longwood Lancers"] <- "Longwood"
TeamsOa$full_name[TeamsOa$full_name == "Louisiana Ragin' Cajuns"] <- "Louisiana"
TeamsOa$full_name[TeamsOa$full_name == "Louisiana Tech Bulldogs"] <- "Louisiana Tech"
TeamsOa$full_name[TeamsOa$full_name == "Louisville Cardinals"] <- "Louisville"
TeamsOa$full_name[TeamsOa$full_name == "Loyola (Chi) Ramblers"] <- "Loyola (Chi)"
TeamsOa$full_name[TeamsOa$full_name == "Loyola (MD) Greyhounds"] <- "Loyola (MD)"
TeamsOa$full_name[TeamsOa$full_name == "Loyola Marymount Lions"] <- "Loyola Marymount"
TeamsOa$full_name[TeamsOa$full_name == "Maine Black Bears"] <- "Maine"
TeamsOa$full_name[TeamsOa$full_name == "Manhattan Jaspers"] <- "Manhattan"
TeamsOa$full_name[TeamsOa$full_name == "Marist Red Foxes"] <- "Marist"
TeamsOa$full_name[TeamsOa$full_name == "Marquette Golden Eagles"] <- "Marquette"
TeamsOa$full_name[TeamsOa$full_name == "Marshall Thundering Herd"] <- "Marshall"
TeamsOa$full_name[TeamsOa$full_name == "Maryland Terrapins"] <- "Maryland"
TeamsOa$full_name[TeamsOa$full_name == "Maryland-Eastern Shore Hawks"] <- "Maryland-Eastern Shore"
TeamsOa$full_name[TeamsOa$full_name == "Massachusetts Minutemen"] <- "Massachusetts"
TeamsOa$full_name[TeamsOa$full_name == "McNeese Cowboys"] <- "McNeese"
TeamsOa$full_name[TeamsOa$full_name == "Memphis Tigers"] <- "Memphis"
TeamsOa$full_name[TeamsOa$full_name == "Mercer Bears"] <- "Mercer"
TeamsOa$full_name[TeamsOa$full_name == "Mercyhurst Lakers"] <- "Mercyhurst"
TeamsOa$full_name[TeamsOa$full_name == "Merrimack Warriors"] <- "Merrimack"
TeamsOa$full_name[TeamsOa$full_name == "Miami (OH) RedHawks"] <- "Miami (OH)"
TeamsOa$full_name[TeamsOa$full_name == "Miami Hurricanes"] <- "Miami"
TeamsOa$full_name[TeamsOa$full_name == "Michigan St Spartans"] <- "Michigan St."
TeamsOa$full_name[TeamsOa$full_name == "Michigan Wolverines"] <- "Michigan"
TeamsOa$full_name[TeamsOa$full_name == "Middle Tennessee Blue Raiders"] <- "Middle Tennessee"
TeamsOa$full_name[TeamsOa$full_name == "Milwaukee Panthers"] <- "Milwaukee"
TeamsOa$full_name[TeamsOa$full_name == "Minnesota Golden Gophers"] <- "Minnesota"
TeamsOa$full_name[TeamsOa$full_name == "Miss Valley St Delta Devils"] <- "Miss Valley St."
TeamsOa$full_name[TeamsOa$full_name == "Mississippi St Bulldogs"] <- "Mississippi St."
TeamsOa$full_name[TeamsOa$full_name == "Missouri St Bears"] <- "Missouri St."
TeamsOa$full_name[TeamsOa$full_name == "Missouri Tigers"] <- "Missouri"
TeamsOa$full_name[TeamsOa$full_name == "Monmouth Hawks"] <- "Monmouth"
TeamsOa$full_name[TeamsOa$full_name == "Montana Grizzlies"] <- "Montana"
TeamsOa$full_name[TeamsOa$full_name == "Montana St Bobcats"] <- "Montana St."
TeamsOa$full_name[TeamsOa$full_name == "Morehead St Eagles"] <- "Morehead St"
TeamsOa$full_name[TeamsOa$full_name == "Morgan St Bears"] <- "Morgan St."
TeamsOa$full_name[TeamsOa$full_name == "Mt. St. Mary's Mountaineers"] <- "Mt. St. Mary's"
TeamsOa$full_name[TeamsOa$full_name == "Murray St Racers"] <- "Murray St."
TeamsOa$full_name[TeamsOa$full_name == "N Colorado Bears"] <- "N Colorado"
TeamsOa$full_name[TeamsOa$full_name == "NC State Wolfpack"] <- "NC St."
TeamsOa$full_name[TeamsOa$full_name == "NJIT Highlanders"] <- "NJIT"
TeamsOa$full_name[TeamsOa$full_name == "Navy Midshipmen"] <- "Navy"
TeamsOa$full_name[TeamsOa$full_name == "Nebraska Cornhuskers"] <- "Nebraska"
TeamsOa$full_name[TeamsOa$full_name == "Nevada Wolf Pack"] <- "Nevada"
TeamsOa$full_name[TeamsOa$full_name == "New Hampshire Wildcats"] <- "New Hampshire"
TeamsOa$full_name[TeamsOa$full_name == "New Haven Chargers"] <- "New Haven"
TeamsOa$full_name[TeamsOa$full_name == "New Mexico Lobos"] <- "New Mexico"
TeamsOa$full_name[TeamsOa$full_name == "New Mexico St Aggies"] <- "New Mexico St."
TeamsOa$full_name[TeamsOa$full_name == "New Orleans Privateers"] <- "New Orleans"
TeamsOa$full_name[TeamsOa$full_name == "Niagara Purple Eagles"] <- "Niagara"
TeamsOa$full_name[TeamsOa$full_name == "Nicholls St Colonels"] <- "Nicholls St."
TeamsOa$full_name[TeamsOa$full_name == "Norfolk St Spartans"] <- "Norfolk St."
TeamsOa$full_name[TeamsOa$full_name == "North Alabama Lions"] <- "North Alabama"
TeamsOa$full_name[TeamsOa$full_name == "North American Stallions"] <- "North American"
TeamsOa$full_name[TeamsOa$full_name == "North Carolina A&T Aggies"] <- "North Carolina A&T"
TeamsOa$full_name[TeamsOa$full_name == "North Carolina Central Eagles"] <- "North Carolina Central"
TeamsOa$full_name[TeamsOa$full_name == "North Carolina Tar Heels"] <- "North Carolina"
TeamsOa$full_name[TeamsOa$full_name == "North Dakota Fighting Hawks"] <- "North Dakota"
TeamsOa$full_name[TeamsOa$full_name == "North Dakota St Bison"] <- "North Dakota St."
TeamsOa$full_name[TeamsOa$full_name == "North Florida Ospreys"] <- "North Florida"
TeamsOa$full_name[TeamsOa$full_name == "North Texas Mean Green"] <- "North Texas"
TeamsOa$full_name[TeamsOa$full_name == "Northeastern Huskies"] <- "Northeastern"
TeamsOa$full_name[TeamsOa$full_name == "Northern Arizona Lumberjacks"] <- "Northern Arizona"
TeamsOa$full_name[TeamsOa$full_name == "Northern Illinois Huskies"] <- "Northern Illinois"
TeamsOa$full_name[TeamsOa$full_name == "Northern Iowa Panthers"] <- "Northern Iowa"
TeamsOa$full_name[TeamsOa$full_name == "Northern Kentucky Norse"] <- "Northern Kentucky"
TeamsOa$full_name[TeamsOa$full_name == "Northwestern St Demons"] <- "Northwestern St."
TeamsOa$full_name[TeamsOa$full_name == "Northwestern Wildcats"] <- "Northwestern"
TeamsOa$full_name[TeamsOa$full_name == "Notre Dame Fighting Irish"] <- "Notre Dame"
TeamsOa$full_name[TeamsOa$full_name == "Oakland Golden Grizzlies"] <- "Oakland"
TeamsOa$full_name[TeamsOa$full_name == "Ohio Bobcats"] <- "Ohio"
TeamsOa$full_name[TeamsOa$full_name == "Ohio State Buckeyes"] <- "Ohio St."
TeamsOa$full_name[TeamsOa$full_name == "Oklahoma Sooners"] <- "Oklahoma"
TeamsOa$full_name[TeamsOa$full_name == "Oklahoma St Cowboys"] <- "Oklahoma St."
TeamsOa$full_name[TeamsOa$full_name == "Old Dominion Monarchs"] <- "Old Dominion"
TeamsOa$full_name[TeamsOa$full_name == "Ole Miss Rebels"] <- "Ole Miss"
TeamsOa$full_name[TeamsOa$full_name == "Omaha Mavericks"] <- "Omaha"
TeamsOa$full_name[TeamsOa$full_name == "Oral Roberts Golden Eagles"] <- "Oral Roberts"
TeamsOa$full_name[TeamsOa$full_name == "Oregon Ducks"] <- "Oregon"
TeamsOa$full_name[TeamsOa$full_name == "Oregon St Beavers"] <- "Oregon St."
TeamsOa$full_name[TeamsOa$full_name == "Pacific Tigers"] <- "Pacific"
TeamsOa$full_name[TeamsOa$full_name == "Penn State Nittany Lions"] <- "Penn St."
TeamsOa$full_name[TeamsOa$full_name == "Pennsylvania Quakers"] <- "Pennsylvania"
TeamsOa$full_name[TeamsOa$full_name == "Pepperdine Waves"] <- "Pepperdine"
TeamsOa$full_name[TeamsOa$full_name == "Pfeiffer Falcons"] <- "Pfeiffer"
TeamsOa$full_name[TeamsOa$full_name == "Pittsburgh Panthers"] <- "Pittsburgh"
TeamsOa$full_name[TeamsOa$full_name == "Portland Pilots"] <- "Portland"
TeamsOa$full_name[TeamsOa$full_name == "Portland St Vikings"] <- "Portland St."
TeamsOa$full_name[TeamsOa$full_name == "Prairie View Panthers"] <- "Prairie View"
TeamsOa$full_name[TeamsOa$full_name == "Presbyterian Blue Hose"] <- "Presbyterian"
TeamsOa$full_name[TeamsOa$full_name == "Princeton Tigers"] <- "Princeton"
TeamsOa$full_name[TeamsOa$full_name == "Providence Friars"] <- "Providence"
TeamsOa$full_name[TeamsOa$full_name == "Purdue Boilermakers"] <- "Purdue"
TeamsOa$full_name[TeamsOa$full_name == "Queens University Royals"] <- "Queens University"
TeamsOa$full_name[TeamsOa$full_name == "Quinnipiac Bobcats"] <- "Quinnipiac"
TeamsOa$full_name[TeamsOa$full_name == "Radford Highlanders"] <- "Radford"
TeamsOa$full_name[TeamsOa$full_name == "Regent University Royals"] <- "Regent University"
TeamsOa$full_name[TeamsOa$full_name == "Rhode Island Rams"] <- "Rhode Island"
TeamsOa$full_name[TeamsOa$full_name == "Rice Owls"] <- "Rice"
TeamsOa$full_name[TeamsOa$full_name == "Richmond Spiders"] <- "Richmond"
TeamsOa$full_name[TeamsOa$full_name == "Rider Broncs"] <- "Rider"
TeamsOa$full_name[TeamsOa$full_name == "Robert Morris Colonials"] <- "Robert Morris"
TeamsOa$full_name[TeamsOa$full_name == "Rutgers Scarlet Knights"] <- "Rutgers"
TeamsOa$full_name[TeamsOa$full_name == "SE Louisiana Lions"] <- "SE Louisiana"
TeamsOa$full_name[TeamsOa$full_name == "SE Missouri St Redhawks"] <- "SE Missouri St"
TeamsOa$full_name[TeamsOa$full_name == "SIU-Edwardsville Cougars"] <- "SIU-Edwardsville"
TeamsOa$full_name[TeamsOa$full_name == "SMU Mustangs"] <- "SMU"
TeamsOa$full_name[TeamsOa$full_name == "Sacramento St Hornets"] <- "Sacramento St."
TeamsOa$full_name[TeamsOa$full_name == "Sacred Heart Pioneers"] <- "Sacred Heart"
TeamsOa$full_name[TeamsOa$full_name == "Saint Joseph's Hawks"] <- "Saint Joseph's"
TeamsOa$full_name[TeamsOa$full_name == "Saint Louis Billikens"] <- "Saint Louis"
TeamsOa$full_name[TeamsOa$full_name == "Saint Mary's Gaels"] <- "Saint Mary's"
TeamsOa$full_name[TeamsOa$full_name == "Saint Peter's Peacocks"] <- "Saint Peter's"
TeamsOa$full_name[TeamsOa$full_name == "Sam Houston St Bearkats"] <- "Sam Houston St."
TeamsOa$full_name[TeamsOa$full_name == "Samford Bulldogs"] <- "Samford"
TeamsOa$full_name[TeamsOa$full_name == "San Diego St Aztecs"] <- "San Diego St."
TeamsOa$full_name[TeamsOa$full_name == "San Diego Toreros"] <- "San Diego"
TeamsOa$full_name[TeamsOa$full_name == "San Francisco Dons"] <- "San Francisco"
TeamsOa$full_name[TeamsOa$full_name == "San JosÃ© St Spartans"] <- "San JosÃ© St."
TeamsOa$full_name[TeamsOa$full_name == "Santa Clara Broncos"] <- "Santa Clara"
TeamsOa$full_name[TeamsOa$full_name == "Savannah St Tigers"] <- "Savannah St."
TeamsOa$full_name[TeamsOa$full_name == "Seattle Redhawks"] <- "Seattle"
TeamsOa$full_name[TeamsOa$full_name == "Seton Hall Pirates"] <- "Seton Hall"
TeamsOa$full_name[TeamsOa$full_name == "Siena Saints"] <- "Siena"
TeamsOa$full_name[TeamsOa$full_name == "Sonoma State Seawolves"] <- "Sonoma St."
TeamsOa$full_name[TeamsOa$full_name == "South Alabama Jaguars"] <- "South Alabama"
TeamsOa$full_name[TeamsOa$full_name == "South Carolina Gamecocks"] <- "South Carolina"
TeamsOa$full_name[TeamsOa$full_name == "South Carolina St Bulldogs"] <- "South Carolina St."
TeamsOa$full_name[TeamsOa$full_name == "South Carolina Upstate Spartans"] <- "South Carolina Upstate"
TeamsOa$full_name[TeamsOa$full_name == "South Dakota Coyotes"] <- "South Dakota"
TeamsOa$full_name[TeamsOa$full_name == "South Dakota St Jackrabbits"] <- "South Dakota St."
TeamsOa$full_name[TeamsOa$full_name == "South Florida Bulls"] <- "South Florida"
TeamsOa$full_name[TeamsOa$full_name == "Southern Illinois Salukis"] <- "Southern Illinois"
TeamsOa$full_name[TeamsOa$full_name == "Southern Indiana Screaming Eagles"] <- "Southern Indiana"
TeamsOa$full_name[TeamsOa$full_name == "Southern Jaguars"] <- "Southern"
TeamsOa$full_name[TeamsOa$full_name == "Southern Miss Golden Eagles"] <- "Southern Miss"
TeamsOa$full_name[TeamsOa$full_name == "Southern Utah Thunderbirds"] <- "Southern Utah"
TeamsOa$full_name[TeamsOa$full_name == "Spalding Golden Eagles"] <- "Spalding"
TeamsOa$full_name[TeamsOa$full_name == "St. Bonaventure Bonnies"] <- "St. Bonaventure"
TeamsOa$full_name[TeamsOa$full_name == "St. Francis (PA) Red Flash"] <- "St. Francis (PA)"
TeamsOa$full_name[TeamsOa$full_name == "St. Francis BKN Terriers"] <- "St. Francis BKN"
TeamsOa$full_name[TeamsOa$full_name == "St. John's Red Storm"] <- "St. John's"
TeamsOa$full_name[TeamsOa$full_name == "St. Thomas (MN) Tommies"] <- "St. Thomas (MN)"
TeamsOa$full_name[TeamsOa$full_name == "Stanford Cardinal"] <- "Stanford"
TeamsOa$full_name[TeamsOa$full_name == "Stephen F. Austin Lumberjacks"] <- "Stephen F. Austin"
TeamsOa$full_name[TeamsOa$full_name == "Stetson Hatters"] <- "Stetson"
TeamsOa$full_name[TeamsOa$full_name == "Stonehill Skyhawks"] <- "Stonehill"
TeamsOa$full_name[TeamsOa$full_name == "Stony Brook Seawolves"] <- "Stony Brook"
TeamsOa$full_name[TeamsOa$full_name == "Syracuse Orange"] <- "Syracuse"
TeamsOa$full_name[TeamsOa$full_name == "TCU Horned Frogs"] <- "TCU"
TeamsOa$full_name[TeamsOa$full_name == "Tarleton State Texans"] <- "Tarleton St."
TeamsOa$full_name[TeamsOa$full_name == "Temple Owls"] <- "Temple"
TeamsOa$full_name[TeamsOa$full_name == "Tenn-Martin Skyhawks"] <- "Tenn-Martin"
TeamsOa$full_name[TeamsOa$full_name == "Tennessee St Tigers"] <- "Tennessee St."
TeamsOa$full_name[TeamsOa$full_name == "Tennessee Tech Golden Eagles"] <- "Tennessee Tech"
TeamsOa$full_name[TeamsOa$full_name == "Tennessee Volunteers"] <- "Tennessee"
TeamsOa$full_name[TeamsOa$full_name == "Texas A&M Aggies"] <- "Texas A&M"
TeamsOa$full_name[TeamsOa$full_name == "Texas A&M-CC Islanders"] <- "Texas A&M-CC"
TeamsOa$full_name[TeamsOa$full_name == "Texas Longhorns"] <- "Texas"
TeamsOa$full_name[TeamsOa$full_name == "Texas Southern Tigers"] <- "Texas Southern"
TeamsOa$full_name[TeamsOa$full_name == "Texas State Bobcats"] <- "Texas St."
TeamsOa$full_name[TeamsOa$full_name == "Texas Tech Red Raiders"] <- "Texas Tech"
TeamsOa$full_name[TeamsOa$full_name == "The Citadel Bulldogs"] <- "The Citadel"
TeamsOa$full_name[TeamsOa$full_name == "Toledo Rockets"] <- "Toledo"
TeamsOa$full_name[TeamsOa$full_name == "Towson Tigers"] <- "Towson"
TeamsOa$full_name[TeamsOa$full_name == "Troy Trojans"] <- "Troy"
TeamsOa$full_name[TeamsOa$full_name == "Tulane Green Wave"] <- "Tulane"
TeamsOa$full_name[TeamsOa$full_name == "Tulsa Golden Hurricane"] <- "Tulsa"
TeamsOa$full_name[TeamsOa$full_name == "UAB Blazers"] <- "UAB"
TeamsOa$full_name[TeamsOa$full_name == "UC Davis Aggies"] <- "UC Davis"
TeamsOa$full_name[TeamsOa$full_name == "UC Irvine Anteaters"] <- "UC Irvine"
TeamsOa$full_name[TeamsOa$full_name == "UC Riverside Highlanders"] <- "UC Riverside"
TeamsOa$full_name[TeamsOa$full_name == "UC San Diego Tritons"] <- "UC San Diego"
TeamsOa$full_name[TeamsOa$full_name == "UC Santa Barbara Gauchos"] <- "UC Santa Barbara"
TeamsOa$full_name[TeamsOa$full_name == "UCF Knights"] <- "UCF"
TeamsOa$full_name[TeamsOa$full_name == "UCLA Bruins"] <- "UCLA"
TeamsOa$full_name[TeamsOa$full_name == "UConn Huskies"] <- "UConn"
TeamsOa$full_name[TeamsOa$full_name == "UIC Flames"] <- "UIC"
TeamsOa$full_name[TeamsOa$full_name == "UL Monroe Warhawks"] <- "UL Monroe"
TeamsOa$full_name[TeamsOa$full_name == "UMBC Retrievers"] <- "UMBC"
TeamsOa$full_name[TeamsOa$full_name == "UMKC Kangaroos"] <- "UMKC"
TeamsOa$full_name[TeamsOa$full_name == "UMass Lowell River Hawks"] <- "UMass Lowell"
TeamsOa$full_name[TeamsOa$full_name == "UNC Asheville Bulldogs"] <- "UNC Asheville"
TeamsOa$full_name[TeamsOa$full_name == "UNC Greensboro Spartans"] <- "UNC Greensboro"
TeamsOa$full_name[TeamsOa$full_name == "UNC Wilmington Seahawks"] <- "UNC Wilmington"
TeamsOa$full_name[TeamsOa$full_name == "UNLV Rebels"] <- "UNLV"
TeamsOa$full_name[TeamsOa$full_name == "USC Trojans"] <- "USC"
TeamsOa$full_name[TeamsOa$full_name == "UT Rio Grande Valley Vaqueros"] <- "UT Rio Grande Valley"
TeamsOa$full_name[TeamsOa$full_name == "UT-Arlington Mavericks"] <- "UT-Arlington"
TeamsOa$full_name[TeamsOa$full_name == "UTEP Miners"] <- "UTEP"
TeamsOa$full_name[TeamsOa$full_name == "UTSA Roadrunners"] <- "UTSA"
TeamsOa$full_name[TeamsOa$full_name == "Utah State Aggies"] <- "Utah St."
TeamsOa$full_name[TeamsOa$full_name == "Utah Tech Trailblazers"] <- "Utah Tech"
TeamsOa$full_name[TeamsOa$full_name == "Utah Utes"] <- "Utah"
TeamsOa$full_name[TeamsOa$full_name == "Utah Valley Wolverines"] <- "Utah Valley"
TeamsOa$full_name[TeamsOa$full_name == "VCU Rams"] <- "VCU"
TeamsOa$full_name[TeamsOa$full_name == "VMI Keydets"] <- "VMI"
TeamsOa$full_name[TeamsOa$full_name == "Valparaiso Beacons"] <- "Valparaiso"
TeamsOa$full_name[TeamsOa$full_name == "Vanderbilt Commodores"] <- "Vanderbilt"
TeamsOa$full_name[TeamsOa$full_name == "Vermont Catamounts"] <- "Vermont"
TeamsOa$full_name[TeamsOa$full_name == "Villanova Wildcats"] <- "Villanova"
TeamsOa$full_name[TeamsOa$full_name == "Virginia Cavaliers"] <- "Virginia"
TeamsOa$full_name[TeamsOa$full_name == "Virginia Tech Hokies"] <- "Virginia Tech"
TeamsOa$full_name[TeamsOa$full_name == "Wagner Seahawks"] <- "Wagner"
TeamsOa$full_name[TeamsOa$full_name == "Wake Forest Demon Deacons"] <- "Wake Forest"
TeamsOa$full_name[TeamsOa$full_name == "Washington Huskies"] <- "Washington"
TeamsOa$full_name[TeamsOa$full_name == "Washington St Cougars"] <- "Washington St."
TeamsOa$full_name[TeamsOa$full_name == "Weber State Wildcats"] <- "Weber St."
TeamsOa$full_name[TeamsOa$full_name == "West Georgia Wolves"] <- "West Georgia"
TeamsOa$full_name[TeamsOa$full_name == "West Virginia Mountaineers"] <- "West Virginia"
TeamsOa$full_name[TeamsOa$full_name == "Western Carolina Catamounts"] <- "Western Carolina"
TeamsOa$full_name[TeamsOa$full_name == "Western Illinois Leathernecks"] <- "Western Illinois"
TeamsOa$full_name[TeamsOa$full_name == "Western Kentucky Hilltoppers"] <- "Western Kentucky"
TeamsOa$full_name[TeamsOa$full_name == "Western Michigan Broncos"] <- "Western Michigan"
TeamsOa$full_name[TeamsOa$full_name == "Western State Colorado Mountaineers"] <- "Western St. Colorado"
TeamsOa$full_name[TeamsOa$full_name == "Wichita St Shockers"] <- "Wichita St."
TeamsOa$full_name[TeamsOa$full_name == "William & Mary Tribe"] <- "William & Mary"
TeamsOa$full_name[TeamsOa$full_name == "Winthrop Eagles"] <- "Winthrop"
TeamsOa$full_name[TeamsOa$full_name == "Wisconsin Badgers"] <- "Wisconsin"
TeamsOa$full_name[TeamsOa$full_name == "Wofford Terriers"] <- "Wofford"
TeamsOa$full_name[TeamsOa$full_name == "Wright St Raiders"] <- "Wright St."
TeamsOa$full_name[TeamsOa$full_name == "Wyoming Cowboys"] <- "Wyoming"
TeamsOa$full_name[TeamsOa$full_name == "Xavier Musketeers"] <- "Xavier"
TeamsOa$full_name[TeamsOa$full_name == "Yale Bulldogs"] <- "Yale"
TeamsOa$full_name[TeamsOa$full_name == "Youngstown St Penguins"] <- "Youngstown St."
TeamsOa$full_name[TeamsOa$full_name == "Arkansas-Pine Bluff"] <- "Arkansas Pine Bluff"
TeamsOa$full_name[TeamsOa$full_name == "Bethune-Cookman"] <- "Bethune Cookman"
TeamsOa$full_name[TeamsOa$full_name == "Boston Univ."] <- "Boston University"
TeamsOa$full_name[TeamsOa$full_name == "CSU Bakersfield"] <- "Cal St. Bakersfield"
TeamsOa$full_name[TeamsOa$full_name == "CSU Fullerton"] <- "Cal St. Fullerton"
TeamsOa$full_name[TeamsOa$full_name == "Central Connecticut St"] <- "Central Connecticut"
TeamsOa$full_name[TeamsOa$full_name == "UConn"] <- "Connecticut"
TeamsOa$full_name[TeamsOa$full_name == "Coppin St"] <- "Coppin St."
TeamsOa$full_name[TeamsOa$full_name == "CSU Northridge"] <- "CSUN"
TeamsOa$full_name[TeamsOa$full_name == "East Tennessee St"] <- "East Tennessee St."
TeamsOa$full_name[TeamsOa$full_name == "Florida Int'l"] <- "FIU"
TeamsOa$full_name[TeamsOa$full_name == "Gardner-Webb"] <- "Gardner Webb"
TeamsOa$full_name[TeamsOa$full_name == "GW"] <- "George Washington"
TeamsOa$full_name[TeamsOa$full_name == "Grambling St"] <- "Grambling St."
TeamsOa$full_name[TeamsOa$full_name == "Hawai'i"] <- "Hawaii"
TeamsOa$full_name[TeamsOa$full_name == "UIC"] <- "Illinois Chicago"
TeamsOa$full_name[TeamsOa$full_name == "IUPUI"] <- "IU Indy"
TeamsOa$full_name[TeamsOa$full_name == "UMKC"] <- "Kansas City"
TeamsOa$full_name[TeamsOa$full_name == "Kennesaw St"] <- "Kennesaw St."
TeamsOa$full_name[TeamsOa$full_name == "Arkansas-Little Rock"] <- "Little Rock"
TeamsOa$full_name[TeamsOa$full_name == "UL Monroe"] <- "Louisiana Monroe"
TeamsOa$full_name[TeamsOa$full_name == "Loyola (Chi)"] <- "Loyola Chicago"
TeamsOa$full_name[TeamsOa$full_name == "Loyola (MD)"] <- "Loyola MD"
TeamsOa$full_name[TeamsOa$full_name == "Maryland-Eastern Shore"] <- "Maryland Eastern Shore"
TeamsOa$full_name[TeamsOa$full_name == "Miami"] <- "Miami FL"
TeamsOa$full_name[TeamsOa$full_name == "Miami (OH)"] <- "Miami OH"
TeamsOa$full_name[TeamsOa$full_name == "Ole Miss"] <- "Mississippi"
TeamsOa$full_name[TeamsOa$full_name == "Miss Valley St."] <- "Mississippi Valley St."
TeamsOa$full_name[TeamsOa$full_name == "Morehead St"] <- "Morehead St."
TeamsOa$full_name[TeamsOa$full_name == "Mt. St. Mary's"] <- "Mount St. Mary's"
TeamsOa$full_name[TeamsOa$full_name == "NC St."] <- "N.C. State"
TeamsOa$full_name[TeamsOa$full_name == "Omaha"] <- "Nebraska Omaha"
TeamsOa$full_name[TeamsOa$full_name == "Nicholls St."] <- "Nicholls"
TeamsOa$full_name[TeamsOa$full_name == "N Colorado"] <- "Northern Colorado"
TeamsOa$full_name[TeamsOa$full_name == "Pennsylvania"] <- "Penn"
TeamsOa$full_name[TeamsOa$full_name == "Prairie View"] <- "Prairie View A&M"
TeamsOa$full_name[TeamsOa$full_name == "Fort Wayne"] <- "Purdue Fort Wayne"
TeamsOa$full_name[TeamsOa$full_name == "Queens University"] <- "Queens"
TeamsOa$full_name[TeamsOa$full_name == "St. Francis (PA)"] <- "Saint Francis"
TeamsOa$full_name[TeamsOa$full_name == "SIU-Edwardsville"] <- "SIUE"
TeamsOa$full_name[TeamsOa$full_name == "SE Missouri St"] <- "Southeast Missouri"
TeamsOa$full_name[TeamsOa$full_name == "SE Louisiana"] <- "Southeastern Louisiana"
TeamsOa$full_name[TeamsOa$full_name == "St. Thomas (MN)"] <- "St. Thomas"
TeamsOa$full_name[TeamsOa$full_name == "Tenn-Martin"] <- "Tennessee Martin"
TeamsOa$full_name[TeamsOa$full_name == "Texas A&M-CC"] <- "Texas A&M Corpus Chris"
TeamsOa$full_name[TeamsOa$full_name == "South Carolina Upstate"] <- "USC Upstate"
TeamsOa$full_name[TeamsOa$full_name == "UT-Arlington"] <- "UT Arlington"
TeamsOa$full_name[TeamsOa$full_name == paste0("San Jos","\u00E9"," St Spartans")] <- "San Jose St."
return(TeamsOa)
}
